### ISSUE TITLE
Problema sobre Recuperar Árvore

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/bekonator#2]
Pessoas, salvar o arquivo está ok já que a condição de parada do algoritmo pre ordem é se o elemento é NULL, porém recuperar a ávore apenas com as informações disponíveis está dificil já que a condição de parada do algoritmo pre ordem não fica clara. Alguém tem ideia de como fazer?

**Comment by iWarhead** [comment]
Estou pensando em algo aqui para resolver isso, vou dar uma pesquisada.

**Comment by aronsales** [comment]
Também estou com essa dúvida alesson, com as informações que nós iremos gravar no arquivo, não há um padrão certo para a reconstrução da árvore.

**Comment by wagner-lucas** [comment]
Eu tbm percebi isso Alesson, eu ainda nao consegui entender, como vamos usar preord, para recuperar a árvore, apenas com as informações salvas no arquivo. Estava olhando e pode ser q tipo, o 1 seja o critério de parada, porem dependendo da ordem que o arquivo esteja salvo, isso nao se encaixa com o sistema de preord.

**Comment by alessonrenato** [comment]
acredito que consegui resolver na funcao leArq
