### ISSUE TITLE
Função inserir 

### ISSUE THREAD

**Issue by aronsales** [alessonrenato/bekonator#3]
Gente, tomem cuidado com a funcao inserir, pois, ao receber uma pergunta, ela n irá funcionar corretamente, deixo este issue como um pedido de ajuda também, caso alguém saiba como corrigir.

**Comment by wagner-lucas** [comment]
Aron a função ta funcionando direito, eu só modifiquei o sentido como estava inserindo. Pois quando tinha um novo dado, estava inserido ao contrario.
