### ISSUE TITLE
Função de perguntas

### ISSUE THREAD

**Issue by iWarhead** [alessonrenato/bekonator#5]
Senhores, adicionei a função que faz as perguntas e percorre a árvore, porém ela ainda precisa ser aprimorada. Any ideas?

**Comment by aronsales** [comment]
Acho que a função atual já está do jeito que nos queríamos, algum colega tem alguma dica?

**Comment by wagner-lucas** [comment]
Eu apenas modifiquei o ponteiro que você estava usando arthur e ficou ok. Melhoramento no commit 22c1273aea3994ca84154e7d4716810836034958
