### ISSUE TITLE
Bug dos animais

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/bekonator#6]
Gente, consegui retirar alguns bugs no programa, mas o programa está inserindo os animais invertidos não e sim.

**Comment by aronsales** [comment]
Percebi isso! Corrigi junto com wagner, a solução já está a caminho!

**Comment by wagner-lucas** [comment]
Alesson corrigimos isso no commit 8de780b48f1737e5babb7f0dc6dfc8ffdbb3d6bf .
